if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug)
endif()


if (CMAKE_BUILD_TYPE MATCHES Debug)
  set(EX_BUILD_TYPE_NAME Debug)
  set(DEBUG ON)
  set(RELEASE OFF)
elseif (CMAKE_BUILD_TYPE MATCHES Release)
  set(EX_BUILD_TYPE_NAME Release)
  set(DEBUG OFF)
  set(RELEASE ON)
else()
  message(FATAL_ERROR Unknown build type "${CMAKE_BUILD_TYPE}")
endif()



if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    SET( EX_PLATFORM 64 )
    SET( EX_PLATFORM_NAME "x64" )
else( CMAKE_SIZEOF_VOID_P EQUAL 8 ) 
    SET( EX_PLATFORM 32 )
    SET( EX_PLATFORM_NAME "x86" )
endif( CMAKE_SIZEOF_VOID_P EQUAL 8 )

set(EX_BUILD_TYPE_FULLNAME ${EX_PLATFORM_NAME}-${EX_BUILD_TYPE_NAME})

MESSAGE( "Build architecture: ${EX_BUILD_TYPE_FULLNAME}")