set(LMDA_VERSION_REGEX "#define LMDA_VERSION_.*[ \t]+(.+)")
set(LMDA_PRERELEASE_REGEX "#define LMDA_VER_PRERELEASE[ \t]+(.+)")
set(LMDA_VERSION_HEADER "${CMAKE_CURRENT_SOURCE_DIR}/include/lmda/version.h")

file(STRINGS "${LMDA_VERSION_HEADER}" LMDA_VERSION REGEX ${LMDA_VERSION_REGEX})
file(STRINGS "${LMDA_VERSION_HEADER}" LMDA_PRERELEASE REGEX ${LMDA_PRERELEASE_REGEX})

list(TRANSFORM LMDA_VERSION REPLACE ${LMDA_VERSION_REGEX} "\\1")
list(TRANSFORM LMDA_PRERELEASE REPLACE ${LMDA_PRERELEASE_REGEX} "\\1")

string(JOIN "." LMDA_VERSION ${LMDA_VERSION})
set(LMDA_VERSION_FULL "v${LMDA_VERSION}-${LMDA_PRERELEASE}")

message("Configuring LMDA ${LMDA_VERSION_FULL}")